
'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, AlertTriangle, FileCheck, DollarSign, Users, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";

const snapshotItems = [
    { type: "risk", title: "Revenue shortfall risk of 8% detected in APAC.", link: "/revenue-risk", icon: DollarSign, color: "text-destructive" },
    { type: "approval", title: "3 SOP updates are pending your approval.", link: "/approvals", icon: FileCheck, color: "text-yellow-500" },
    { type: "compliance", title: "ESG reporting is overdue by 5 days.", link: "/compliance", icon: AlertTriangle, color: "text-destructive" },
    { type: "capacity", title: "Sales department workload is at 120% capacity.", link: "/heatmaps", icon: Users, color: "text-yellow-500" },
];

export default function ExecutiveSnapshotPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight font-headline">Executive Snapshot</h1>
        <p className="text-muted-foreground">Your daily/weekly AI-curated list of the most critical items needing your attention.</p>
      </div>

      <Card>
        <CardHeader>
            <CardTitle className="flex items-center gap-2"><Bot className="text-primary"/>Today's Snapshot for CEO</CardTitle>
            <CardDescription>Generated by AI on July 29, 2024. These are the top 4 items requiring your focus.</CardDescription>
        </CardHeader>
        <CardContent>
            <ul className="space-y-4">
                {snapshotItems.map(item => (
                    <li key={item.title} className="flex items-center justify-between p-4 border rounded-lg hover:bg-secondary/50 transition-colors">
                        <div className="flex items-center gap-4">
                            <item.icon className={`h-6 w-6 flex-shrink-0 ${item.color}`} />
                            <div>
                                <p className="font-semibold">{item.title}</p>
                            </div>
                        </div>
                        <Button variant="ghost" size="sm">
                            Drill Down <ChevronRight className="ml-2 h-4 w-4"/>
                        </Button>
                    </li>
                ))}
            </ul>
        </CardContent>
      </Card>
    </div>
  );
}
